apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monarch

resources:
  - manifests/clusterrole.yaml
  - manifests/rolebinding.yaml
  - manifests/deployment.yaml

configMapGenerator:
  - name: slice-info-config
    behavior: create
    files:
      - slice_info.json
    options:
      disableNameSuffixHash: true
