alertmanager:
  enabled: false

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 32111
  serviceMonitor:
    interval: 10s

prometheus:
  enabled: true

  thanosService:
    enabled: true

  thanosServiceMonitor:
    enabled: true
    type: NodePort
  
  thanosServiceExternal:
    enabled: true
    type: NodePort

  service:
    type: NodePort

  prometheusSpec:
    externalLabels:
      cluster: CN

    scrapeInterval: 10s
    serviceMonitorSelectorNilUsesHelmValues: false
    nodeSelector: 
      nodetype: access

    thanos:
      image: "quay.io/thanos/thanos:v0.24.0"
      version: v0.24.0
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
