apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-1
  # labels:
  #   app: my-example-prometheus
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-storage
  local:
    path: /mnt/data/prometheus-pv-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cn203