apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "kafka-cluster-kafka-bootstrap:9092"
        topics => ["my-topic", "filebeat"]
        decorate_events => basic
        consumer_threads => 1
        group_id => "0"
        codec => "json"
      }
    }
    filter {
      json {
        source => "message"

      }

      if [component] == "SMF" {

        # get S-NSSAI to identify a network slice
        mutate { 
            add_field => { 
              "S-NSSAI" => "%{[slice-session-info][Snssai][SST]}@%{[slice-session-info][Snssai][SD]}"
            } 
        }

        # get F-SEID to identify a PFCP session
        mutate { 
            add_field => { 
              "F-SEID" => "%{[slice-session-info][PFCPSession][Fseid][RemoteSEID]}@%{[slice-session-info][PFCPSession][Fseid][IPAddress]}"
            } 
        }

      }

    }
    output {
      elasticsearch {
        index => "logstash-%{[@metadata][kafka][topic]}"
        hosts => [ "${ES_HOSTS}" ]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        cacert => '/etc/logstash/certificates/ca.crt'
      }

      # Use for debugging
      stdout {}

    }